import { Game } from "@/app/goals";

export const GOLD_TIMES: ReadonlyArray<[Game, number]> = [
  ["nightmanor", 2.5],
  ["mortolii", 2.5],
  ["waldorfsjourney", 2.5],
  ["bushidoball", 3.5],
  ["velgress", 3],
  ["mooncat", 4],
  ["magicgarden", 5],
  ["pingolf", 5],
  ["quibblerace", 5],
  ["barbuta", 5.5],
  ["camouflage", 5.5],
  ["hotfoot", 6],
  ["overbold", 7],
  ["hypercontender", 8],
  ["starwaspir", 8],
  ["ninpek", 8.5],
  ["thebigbellrace", 8.5],
  ["oniondelivery", 10],
  ["rakshasa", 10],
  ["campanella", 13],
  ["caramelcaramel", 12],
  ["kickclub", 13],
  ["seasidedrive", 14],
  ["campanella2", 13],
  ["campanella3", 14],
  ["fisthell", 13],
  ["elfazarshat", 13],
  ["planetzoldath", 15],
  ["avianos", 15],
  ["bughunter", 12],
  ["devilition", 18],
  ["partyhouse", 18],
  ["cyberowls", 20],
  ["miniandmax", 25],
  ["paintchase", 20],
  ["mortol", 30],
  ["attactics", 30],
  ["golfaria", 35],
  ["combatants", 35],
  ["warptank", 40],
  ["railheist", 40],
  ["porgy", 45],
  ["blockkoala", 60],
  ["divers", 60],
  ["vainger", 60],
  ["rockonisland", 60],
  ["valbrace", 70],
  ["grimstone", 120],
  ["lordsofdiskonia", 180],
  ["pilotquest", 240],
];

export const CHERRY_TIMES: ReadonlyArray<[Game, number]> = [
  ["mortolii", 3],
  ["bushidoball", 3.5],
  ["waldorfsjourney", 3.5],
  ["velgress", 4],
  ["magicgarden", 5],
  ["pingolf", 5],
  ["barbuta", 5.5],
  ["hotfoot", 6],
  ["quibblerace", 6],
  ["overbold", 7],
  ["nightmanor", 7],
  ["starwaspir", 8],
  ["thebigbellrace", 8.5],
  ["rakshasa", 10],
  ["kickclub", 13],
  ["fisthell", 13],
  ["campanella2", 13],
  ["caramelcaramel", 14],
  ["elfazarshat", 14],
  ["seasidedrive", 14],
  ["campanella3", 14],
  ["planetzoldath", 15],
  ["camouflage", 15],
  ["mooncat", 16],
  ["campanella", 16],
  ["oniondelivery", 16],
  ["hypercontender", 16],
  ["ninpek", 17.5],
  ["devilition", 18],
  ["paintchase", 20],
  ["cyberowls", 20],
  ["partyhouse", 25],
  ["bughunter", 30],
  ["mortol", 30],
  ["avianos", 40],
  ["attactics", 60],
  ["divers", 60],
  ["railheist", 60],
  ["vainger", 60],
  ["miniandmax", 60],
  ["combatants", 60],
  ["blockkoala", 70],
  ["golfaria", 70],
  ["valbrace", 70],
  ["warptank", 80],
  ["rockonisland", 80],
  ["porgy", 90],
  ["grimstone", 180],
  ["lordsofdiskonia", 240],
  ["pilotquest", 240],
];

export const GIFT_TIMES: ReadonlyArray<[Game, string]> = [
  ["magicgarden", "10 oppies"],
  ["blockkoala", "Custom"],
  ["pingolf", "Hole-in-one"],
  ["ninpek", "3 sandwiches"],
  ["avianos", "Max blessing"],
  ["mooncat", "1 warp"],
  ["thebigbellrace", "1st place"],
  ["waldorfsjourney", "50%"],
  ["divers", "Parasite Hammer"],
  ["rakshasa", "3 revives"],
  ["starwaspir", "10x"],
  ["nightmanor", "Escape killer"],
  ["cyberowls", "1 rescue"],
  ["bushidoball", "3 rounds"],
  ["mortolii", "Switch"],
  ["quibblerace", "Sponsor win"],
  ["velgress", "2 keys"],
  ["valbrace", "Level 8"],
  ["golfaria", "Block Buster"],
  ["vainger", "Heat mod"],
  ["overbold", "Win 500+"],
  ["campanella", "15 lives"],
  ["caramelcaramel", "Egg"],
  ["seasidedrive", "Win bonus"],
  ["campanella3", "Win bonus"],
  ["oniondelivery", "2 days"],
  ["hotfoot", "3 rounds"],
  ["miniandmax", "100 shinies"],
  ["partyhouse", "1 win"],
  ["elfazarshat", "Win bonus"],
  ["bughunter", "1 job"],
  ["fisthell", "9 rounds"],
  ["pilotquest", "Unktomi"],
  ["campanella2", "Friendship"],
  ["barbuta", "25 rooms"],
  ["camouflage", "30%"],
  ["porgy", "Boss"],
  ["planetzoldath", "1 Map"],
  ["hypercontender", "Draft"],
  ["kickclub", "Track World"],
  ["combatants", "Spider"],
  ["devilition", "5 levels"],
  ["paintchase", "12 levels"],
  ["railheist", "10 levels"],
  ["mortol", "2-C"],
  ["attactics", "12 levels"],
  ["grimstone", "10 level ups"],
  ["warptank", "Renegade"],
  ["rockonisland", "Dino Camp"],
  ["lordsofdiskonia", "5 levels"],
  // ["magicgarden", 0.5],
  // ["blockkoala", 0.5],
  // ["pingolf", 0.5],
  // ["ninpek", 1],
  // ["avianos", 1],
  // ["mooncat", 1],
  // ["thebigbellrace", 1],
  // ["waldorfsjourney", 1],
  // ["divers", 1],
  // ["rakshasa", 1],
  // ["starwaspir", 1],
  // ["nightmanor", 1],
  // ["cyberowls", 1],
  // ["bushidoball", 1.5],
  // ["mortolii", 1.5],
  // ["quibblerace", 1.5],
  // ["velgress", 2],
  // ["valbrace", 2],
  // ["golfaria", 2.5],
  // ["vainger", 2.5],
  // ["overbold", 2.5],
  // ["campanella", 2.8],
  // ["caramelcaramel", 3],
  // ["seasidedrive", 3],
  // ["campanella3", 3],
  // ["oniondelivery", 3],
  // ["hotfoot", 3],
  // ["miniandmax", 3],
  // ["partyhouse", 3.5],
  // ["elfazarshat", 3.5],
  // ["bughunter", 3.8],
  // ["fisthell", 4],
  // ["pilotquest", 4],
  // ["campanella2", 4.5],
  // ["barbuta", 5],
  // ["camouflage", 5],
  // ["porgy", 5],
  // ["planetzoldath", 6],
  // ["hypercontender", 6],
  // ["kickclub", 7],
  // ["combatants", 7],
  // ["devilition", 8],
  // ["paintchase", 9],
  // ["railheist", 12],
  // ["mortol", 13],
  // ["attactics", 20],
  // ["grimstone", 20],
  // ["warptank", 30],
  // ["rockonisland", 30],
  // ["lordsofdiskonia", 60],
];

export const TOP_3: ReadonlyArray<[Game, string]> = [
  ["magicgarden", "8k"],
  ["ninpek", "8k"],
  ["starwaspir", "100k"],
  ["campanella", "15k"],
  ["kickclub", "75k"],
  ["rakshasa", "30k"],
  ["seasidedrive", "100k"],
  ["caramelcaramel", "60k"],
  ["paintchase", "320"],
];

export const TOP_5: ReadonlyArray<[Game, string]> = [
  ["campanella", "5k"],
  ["magicgarden", "6k"],
  ["ninpek", "5k"],
  ["starwaspir", "60k"],
  ["caramelcaramel", "20k"],
  ["kickclub", "25k"],
  ["rakshasa", "10k"],
  ["seasidedrive", "40k"],
  ["paintchase", "240"],
];

export const SPORT: ReadonlyArray<Game> = [
  "bushidoball",
  "pingolf",
  "hotfoot",
  "hypercontender",
  "thebigbellrace",
];

export const ARCADE: ReadonlyArray<Game> = [
  "waldorfsjourney",
  "velgress",
  "magicgarden",
  "overbold",
  "starwaspir",
  "ninpek",
  "oniondelivery",
  "campanella",
  "caramelcaramel",
  "kickclub",
  "seasidedrive",
  "campanella3",
  "fisthell",
  "elfazarshat",
  "paintchase",
  "attactics",
];

export const TWO_LEVELS: ReadonlyArray<Game> = [
  "campanella",
  "pingolf",
  "kickclub",
  "mooncat",
  "overbold",
  "devilition",
  "camouflage",
  "warptank",
  "railheist",
  "attactics",
  "bushidoball",
  "hypercontender",
  "campanella3",
  "blockkoala",
  "paintchase",
  "hotfoot",
  "velgress",
  "thebigbellrace",
  "starwaspir",
  "campanella2",
  "combatants",
  "oniondelivery",
  "cyberowls",
  "bughunter",
  "avianos",
  "mortol",
  "rockonisland",
  "lordsofdiskonia",
  "valbrace",
  "partyhouse",
  "caramelcaramel",
  "fisthell",
  "elfazarshat",
  "seasidedrive",
  "rakshasa",
];

export const FOUR_LEVELS: ReadonlyArray<Game> = [
  "campanella",
  "pingolf",
  "kickclub",
  "mooncat",
  "overbold",
  "devilition",
  "camouflage",
  "warptank",
  "railheist",
  "attactics",
  "bushidoball",
  "hypercontender",
  "campanella3",
  "blockkoala",
  "paintchase",
  "hotfoot",
  "velgress",
  "thebigbellrace",
  "starwaspir",
  "campanella2",
  "combatants",
  "oniondelivery",
  "cyberowls",
  "bughunter",
  "avianos",
  "mortol",
  "rockonisland",
  "lordsofdiskonia",
  "valbrace",
  "partyhouse",
  "caramelcaramel",
  "fisthell",
  "elfazarshat",
  "seasidedrive",
];

export const EIGHT_LEVELS: ReadonlyArray<Game> = [
  "campanella",
  "pingolf",
  "kickclub",
  "mooncat",
  "overbold",
  "devilition",
  "camouflage",
  "warptank",
  "railheist",
  "attactics",
  "hypercontender",
  "campanella3",
  "blockkoala",
  "paintchase",
  "thebigbellrace",
  "campanella2",
  "combatants",
  "bughunter",
  "avianos",
  "mortol",
  "rockonisland",
  "lordsofdiskonia",
  "partyhouse",
];

export const BEVERAGE: ReadonlyArray<Game> = [
  "divers",
  "campanella",
  "magicgarden",
  "lordsofdiskonia",
  "hotfoot",
  "valbrace",
  "miniandmax",
  "warptank",
  "ninpek",
  "grimstone",
];

export const FOOD: ReadonlyArray<Game> = [
  "kickclub",
  "ninpek",
  "waldorfsjourney",
  "fisthell",
  "combatants",
  "rockonisland",
  "cyberowls",
  "camouflage",

  "planetzoldath",
  "grimstone",
  "valbrace",
  "campanella2",
  "pilotquest",
  "miniandmax",
  "barbuta",
];

export const KEYS: ReadonlyArray<Game> = [
  "mortolii",
  "valbrace",
  "waldorfsjourney",
  "velgress",
  "cyberowls",
  "barbuta",
  "nightmanor",

  "miniandmax",
  "vainger",
  "campanella2",
  "grimstone",
];

export const TWO_CHESTS: ReadonlyArray<Game> = [
  "valbrace",
  "divers",
  "nightmanor",
  "barbuta",
  "grimstone",
  "waldorfsjourney",
  "campanella2",
  "pilotquest",
  "elfazarshat",
];

export const SHOPS: ReadonlyArray<Game> = [
  "divers",
  "partyhouse",
  "quibblerace",
  "avianos",
  "bughunter",
  "waldorfsjourney",
  "rockonisland",
  "grimstone",
  "lordsofdiskonia",
  "pilotquest",
  "miniandmax",

  "overbold",
  "velgress",
  "campanella2",
  "fisthell",
  "barbuta",
  "planetzoldath",
  "valbrace",
];

export const UFOS: ReadonlyArray<Game> = [
  "starwaspir",
  "pingolf",
  "oniondelivery",
  "fisthell",
  "golfaria",

  "rakshasa",
  "elfazarshat",
  "partyhouse",
  "seasidedrive",
  "divers",
  "nightmanor",
];

export const LIVES: ReadonlyArray<Game> = [
  "mortol",
  "waldorfsjourney",
  "campanella",
  "cyberowls",
  "kickclub",
  "rakshasa",
  "caramelcaramel",
  "starwaspir",
  "ninpek",

  "vainger",
  "elfazarshat",
  "seasidedrive",
  "campanella3",
  "paintchase",
  "barbuta",
];

export const EGGS: ReadonlyArray<Game> = [
  "barbuta",
  "thebigbellrace",
  "divers",
  "starwaspir",
  "ninpek",
  "oniondelivery",
  "campanella2",
  "rakshasa",
  "caramelcaramel",
  "bughunter",

  "miniandmax",
  "nightmanor",
  "avianos",
  "mooncat",
  "porgy",
  "valbrace",
  "elfazarshat",
  "campanella3",
];

export const HP: ReadonlyArray<Game> = [
  "porgy",
  "planetzoldath",
  "elfazarshat",
  "lordsofdiskonia",
  "golfaria",
  "overbold",
  "miniandmax",
  "grimstone",
  "divers",

  "miniandmax",
  "vainger",
  "valbrace",
];

export const BOSS: ReadonlyArray<Game> = [
  "campanella",
  "starwaspir",
  "fisthell",
  "miniandmax",
  "cyberowls",
  "elfazarshat",
  "rakshasa",
  "pilotquest",

  "railheist", // LAZY-COPS
  "mortol", // OPEN-TOMB
  "blockkoala", // WORM-1234
  "paintchase", // EVEN-COAT

  "seasidedrive",
  "mortolii",
  "vainger",
  "campanella3",
  "velgress",
  "kickclub",
  "caramelcaramel",
  "mooncat",
  "porgy",
  "hotfoot",
  "barbuta",
  "rockonisland",
  "overbold",
  "ninpek",
  "valbrace",

  "nightmanor",
  "grimstone",
  "devilition",
  "campanella2",
  "divers",
  "golfaria",
  "warptank",
  "lordsofdiskonia",
];

export const TWO_BOSSES: ReadonlyArray<Game> = [
  "campanella",
  "starwaspir",
  "fisthell",
  "cyberowls",
  "rakshasa",
  "seasidedrive",
  "campanella3",
  "kickclub",
  "vainger",
  "miniandmax",
  "caramelcaramel",
  "mooncat",
  "pilotquest",

  "elfazarshat",
  "rockonisland",
  "porgy",
  "ninpek",
  "valbrace",
  "warptank",
  "divers",
  "grimstone",
];
