export const BLITZ_UFO = {
  goals: {
    medium: {
      barbuta: [
        "BARBUTA: Collect 300 gold",
        "BARBUTA: Die to the Red Phantom (Small Map Square)",
        "BARBUTA: Fill 4 item slots (you start at 1)",
        "BARBUTA: Kill 10 enemies",
        "BARBUTA: Visit at least 25 rooms",
      ],
      bughunter: [
        "BUG HUNTER: Buy 7 different modules",
        "BUG HUNTER: Complete your first job",
        "BUG HUNTER: End 2 days with 0 bugs alive",
        "BUG HUNTER: Have 3 energy end up on the same tile",
        "BUG HUNTER: Kill 5 bugs using non-attack modules",
      ],
      ninpek: [
        "NINPEK: Break 5 spike blocks",
        "NINPEK: Collect some coffee in a bonus area",
        "NINPEK: Eat 3 sandwiches",
        "NINPEK: Kill 7 enemies while dead in one playthrough",
        "NINPEK: Score 5,000+ points",
      ],
      paintchase: [
        "PAINT CHASE: Activate the same power-up tile 3 times in one life (by repainting it)",
        "PAINT CHASE: Beat 6 levels",
        "PAINT CHASE: Complete a level that has power-up tiles without using any of them",
        "PAINT CHASE: Get 30+ points from a single level",
        "PAINT CHASE: Get an extra life by getting 120+ points",
      ],
      magicgarden: [
        "MAGIC GARDEN: Kill 4 mushrooms",
        "MAGIC GARDEN: Obtain a score multiplier of 4x",
        "MAGIC GARDEN: Reach a score of 10,000+",
        "MAGIC GARDEN: Save 10+ Oppies at once twice",
        "MAGIC GARDEN: Save 100 Oppies in a run",
      ],
      mortol: [
        "MORTOL: Clear 1-A",
        "MORTOL: Clear 2-B using OPEN-TOMB",
        "MORTOL: End a level with 30 or more lives",
        "MORTOL: Get 5 lives by killing enemies",
        "MORTOL: Use LEAF-HEAD, turn 5 enemies into vines",
      ],
      velgress: [
        "VELGRESS: Bounce on the giant squid",
        "VELGRESS: Buy 5 items from shops",
        "VELGRESS: Collect 2 keys in a single run",
        "VELGRESS: Hold 40 coins at once",
        "VELGRESS: Use 5 jump pads",
      ],
      planetzoldath: [
        "PLANET ZOLDATH: Collect a Map Piece",
        "PLANET ZOLDATH: Eat 7 slabs of meat",
        "PLANET ZOLDATH: Gather 4 tools on the floor of the same screen",
        "PLANET ZOLDATH: Max out health by collecting 4 energy cubes",
        "PLANET ZOLDATH: Trade with an NPC",
      ],
      attactics: [
        "ATTACTICS: Beat 8 levels",
        "ATTACTICS: Have 5 promoted units alive at once",
        "ATTACTICS: Have at least 10 Grunts in formation",
        "ATTACTICS: Reach Corporal in ranked mode (Rank 30)",
        "ATTACTICS: Score 500+ points in Survival Mode",
      ],
      devilition: [
        "DEVILITION: Beat Round 4",
        "DEVILITION: Beat the first round in under a minute",
        "DEVILITION: Have 3 of the same piece to choose from",
        "DEVILITION: Have 4 villagers at once",
        "DEVILITION: Kill 4 demons with one piece",
      ],
      kickclub: [
        "KICK CLUB: Beat 3 levels without picking up the ball (using headbonks and slides)",
        "KICK CLUB: Beat Racket World",
        "KICK CLUB: Eat 3 hidden desserts",
        "KICK CLUB: Eat 7 hot dogs",
        "KICK CLUB: Score 25,000 points",
      ],
      avianos: [
        "AVIANOS: Create 20 units with Quetzal's Muster",
        "AVIANOS: Enter combat with extra reserves (>40 units)",
        "AVIANOS: Kill 10 units with Tri-lock's lightning",
        "AVIANOS: Max out blessings from one Ancestor",
        "AVIANOS: Win a Hatchling game",
      ],
      mooncat: [
        "MOONCAT: Beat an underwater level",
        "MOONCAT: Cross the wizard's bridge (main path)",
        "MOONCAT: Defeat 5 unique enemy types",
        "MOONCAT: Use a warp (hidden near flowers)",
        "MOONCAT: Visit 10 different rooms",
      ],
      bushidoball: [
        "BUSHIDO BALL: Beat round 1 with 3 different characters (solo)",
        "BUSHIDO BALL: Beat round 2 on Hyper Speed",
        "BUSHIDO BALL: Beat round 3 with default settings",
        "BUSHIDO BALL: Score a point with a 3-point charged special attack",
        "BUSHIDO BALL: Win a 2P tournament",
      ],
      blockkoala: [
        "BLOCK KOALA: Beat 2 story levels as Koalarana (Pink Koala)",
        "BLOCK KOALA: Beat 5 story levels",
        "BLOCK KOALA: Make 3 different blocks into metal 5 blocks",
        "BLOCK KOALA: Make and beat a custom level",
        "BLOCK KOALA: Using WORM-1234, clear any level numbered 30 or higher",
      ],
      camouflage: [
        "CAMOUFLAGE: Beat Oasis (Level 9)",
        "CAMOUFLAGE: Collect 8 oranges",
        "CAMOUFLAGE: Get eaten by Frog, Gator, & Bird",
        "CAMOUFLAGE: Reach 50% completion or more",
        "CAMOUFLAGE: Save 4 babies",
      ],
      campanella: [
        "CAMPANELLA: Collect 5 hidden coffees",
        "CAMPANELLA: Defeat the Stage A Boss",
        "CAMPANELLA: Defeat the Stage B Boss",
        "CAMPANELLA: Have 10 lives",
        "CAMPANELLA: Score 15,000 points",
      ],
      golfaria: [
        "GOLFARIA: Collect 2 clubs",
        "GOLFARIA: Destroy 2 parbots",
        "GOLFARIA: Hit 5 birdies or eagles",
        "GOLFARIA: Obtain the Brakes",
        "GOLFARIA: Rescue 2 green balls",
      ],
      thebigbellrace: [
        "THE BIG BELL RACE: Collect each of the 5 different powerups",
        "THE BIG BELL RACE: Finish a race while an opponent has 3+ laps left",
        "THE BIG BELL RACE: Get 40 points",
        "THE BIG BELL RACE: Gold disk",
        "THE BIG BELL RACE: Win 3 different courses without dying",
      ],
      warptank: [
        "WARPTANK: Beat 6 levels",
        "WARPTANK: Beat Orb Sector",
        "WARPTANK: Change your Warptank's color",
        "WARPTANK: Collect a coffee (must beat level with it)",
        "WARPTANK: Complete the three levels in the initial hub room",
      ],
      waldorfsjourney: [
        "WALDORF’S JOURNEY: Collect 3 puffins in one run",
        "WALDORF’S JOURNEY: Open a chest",
        "WALDORF’S JOURNEY: Reach at least 50%",
        "WALDORF’S JOURNEY: Read 5 signs",
        "WALDORF’S JOURNEY: Use four unique items in one run",
      ],
      porgy: [
        "PORGY: Collect 3 fuel tanks",
        "PORGY: Collect 3 torpedo upgrades",
        "PORGY: Collect the Buster Torpedos",
        "PORGY: Retrieve the Missiles from the lower right caves",
        "PORGY: Return 3 fish eggs to their mother",
      ],
      oniondelivery: [
        "ONION DELIVERY: Complete day 1",
        "ONION DELIVERY: Complete day 2",
        "ONION DELIVERY: Deliver 20 onions total (can be different runs)",
        "ONION DELIVERY: Deliver 8 onions in a single day and complete the day",
        "ONION DELIVERY: Heal 8 HP without dying",
      ],
      caramelcaramel: [
        "CARAMEL CARAMEL: Beat the Cookie or the Egg",
        "CARAMEL CARAMEL: Get hurt and heal by snapping a red enemy's pic",
        "CARAMEL CARAMEL: Score 20,000 points",
        "CARAMEL CARAMEL: Score 5,000 points in the prologue",
        "CARAMEL CARAMEL: Snap 8 bonus background elements",
      ],
      partyhouse: [
        "PARTY HOUSE: Beat a scenario",
        "PARTY HOUSE: Get any guest to 9 popularity",
        "PARTY HOUSE: Get busted by the fire department",
        "PARTY HOUSE: Have 6 trouble in your party at once",
        "PARTY HOUSE: Max out popularity and cash at the same time",
      ],
      hotfoot: [
        "HOT FOOT: Get a blowout",
        "HOT FOOT: Make the coach stop you from stalling by hoarding",
        "HOT FOOT: Use 7 Special Throws or Abilities",
        "HOT FOOT: Win 3 games in a row",
        "HOT FOOT: Win a game using Draft mode",
      ],
      divers: [
        "DIVERS: Bring back any Pearl",
        "DIVERS: Kill a Slime Eel",
        "DIVERS: Level up a Diver",
        "DIVERS: Obtain any Lance weapon",
        "DIVERS: Purchase Godblood",
      ],
      railheist: [
        "RAIL HEIST: Beat 5 levels",
        "RAIL HEIST: Beat a level while bringing back a money crate intact",
        "RAIL HEIST: Collect 6 badges",
        "RAIL HEIST: Kill a chicken",
        "RAIL HEIST: Use LAZY-COPS; Beat Root Around & Sitting Ducks",
      ],
      vainger: [
        "VAINGER: Collect 2 shield upgrades",
        "VAINGER: Read 10 different terminals",
        "VAINGER: Recharge at 5 different checkpoints",
        "VAINGER: Visit Latom Sector (via the top left corner)",
        "VAINGER: Visit Verde Sector (via either bottom corner",
      ],
      rockonisland: [
        "ROCK ON! ISLAND: Beat Initial Encounter",
        "ROCK ON! ISLAND: Have 15 chickens at once in a main level",
        "ROCK ON! ISLAND: Have all 10 different cavemen built at once in a main level",
        "ROCK ON! ISLAND: Use CLUB-PASS; beat Crossroads",
        "ROCK ON! ISLAND: Use CLUB-PASS; beat Oasis",
      ],
      pingolf: [
        "PINGOLF: Be in first place in the standings immediately after hole 9",
        "PINGOLF: Destroy 8 orange obstacles",
        "PINGOLF: Gold disk",
        "PINGOLF: Score par or less on 4 courses",
        "PINGOLF: Slam dunk the ball into the hole on 6 courses",
      ],
      mortolii: [
        "MORTOL II: Activate a switch",
        "MORTOL II: Collect 5 keys",
        "MORTOL II: Defeat the Cyclops Minotaur miniboss (straight right from the start)",
        "MORTOL II: In one run, defeat at least 2 enemies with each player class",
        "MORTOL II: Unlock 3 doors",
      ],
      fisthell: [
        "FIST HELL: Clear 2nd Scare",
        "FIST HELL: Clear the first scare",
        "FIST HELL: Get money by collecting food at full health",
        "FIST HELL: Have $30 at once",
        "FIST HELL: Survive 6 waves in the gym (left of start)",
      ],
      overbold: [
        "OVERBOLD: Achieve max health, through health upgrades or medkits",
        "OVERBOLD: Buy 7 different upgrades in one run",
        "OVERBOLD: Buy a price hiked item",
        "OVERBOLD: Complete a wave with $500+ stakes",
        "OVERBOLD: Complete round 7",
      ],
      campanella2: [
        "CAMPANELLA 2: Clear Burrows II",
        "CAMPANELLA 2: Clear Moire Woods I or Rink I",
        "CAMPANELLA 2: Have 300 coins",
        "CAMPANELLA 2: Obtain 3 different upgrades in one run (squares in the top left)",
        "CAMPANELLA 2: Upgrade your max health or max fuel",
      ],
      hypercontender: [
        "HYPER CONTENDER: Beat Draft Mode (Default settings)",
        "HYPER CONTENDER: Win 3 tournament fights in in a row with no rematches",
        "HYPER CONTENDER: Win a fight using code PAST-RULE",
        "HYPER CONTENDER: Win a tournament fight with 5 different characters",
        "HYPER CONTENDER: Win Round 4 of the Tournament",
      ],
      valbrace: [
        "VALBRACE: Buy something from the crone",
        "VALBRACE: Clear Floor 1",
        "VALBRACE: Defeat the crone (steal from her)",
        "VALBRACE: Give the Red Knight 3 items",
        "VALBRACE: Level up at a throne",
      ],
      rakshasa: [
        "RAKSHASA: Beat the Bridge Demon",
        "RAKSHASA: Beat the first stage",
        "RAKSHASA: Revive yourself 4 times in one run",
        "RAKSHASA: Score 10,000",
        "RAKSHASA: Use each of the three weapon types in one run",
      ],
      starwaspir: [
        "STAR WASPIR: Clear Wave 1 with the Gray Ship",
        "STAR WASPIR: Clear wave 1 with the Red Ship",
        "STAR WASPIR: Clear wave 1 with the Yellow Ship",
        "STAR WASPIR: Clear wave 2",
        "STAR WASPIR: Have a 10x multiplier",
      ],
      grimstone: [
        "GRIMSTONE: Defeat 15 enemies",
        "GRIMSTONE: Learn 3 Skills",
        "GRIMSTONE: Put money in the bank in Santonio (north)",
        "GRIMSTONE: Reach Level 3 with any character",
        "GRIMSTONE: Talk to the Angel Zad in Mission Francesco (south)",
      ],
      lordsofdiskonia: [
        "LORDS OF DISKONIA: Have 25+ gold",
        "LORDS OF DISKONIA: Make an enemy disk drown",
        "LORDS OF DISKONIA: Win a Quick Battle on Knight difficulty",
        "LORDS OF DISKONIA: Win a Quick Battle on Squire difficulty",
        "LORDS OF DISKONIA: Win the first story mission",
      ],
      nightmanor: [
        "NIGHT MANOR: Collect a gem (Diamond, Topaz, Ruby, or Emerald)",
        "NIGHT MANOR: Find 5 journal entries",
        "NIGHT MANOR: Gold disk",
        "NIGHT MANOR: Have 10 different items (multiple journal entries doesn't count)",
        "NIGHT MANOR: Successfully hide from the killer",
      ],
      elfazarshat: [
        "ELFAZAR’S HAT: Beat the tree stump miniboss",
        "ELFAZAR’S HAT: Clear the first stage",
        "ELFAZAR’S HAT: Earn a continue in the bonus round",
        "ELFAZAR’S HAT: Have three level 2 upgrades active at once",
        "ELFAZAR’S HAT: Kill 3 enemies using bombs",
      ],
      pilotquest: [
        "PILOT QUEST: Collect 3 Zoldnaks",
        "PILOT QUEST: Have 5 Moon Ingots",
        "PILOT QUEST: Have 50 Moon Drops in the Wild Zone",
        "PILOT QUEST: Open a chest",
        "PILOT QUEST: Plant 4 seeds at the crash site",
      ],
      miniandmax: [
        "MINI & MAX: Collect any 4 upgrades",
        "MINI & MAX: Cure Max's fleas",
        "MINI & MAX: Rid the books of Silverfish",
        "MINI & MAX: Stand on the hanging lamp in the upper right",
        "MINI & MAX: Talk to 20 NPCs",
      ],
      combatants: [
        "COMBATANTS: Beat ‘First Blood’",
        "COMBATANTS: Beat ‘Skirmish’",
        "COMBATANTS: Have an army of 5+ NPC Soldier Ants",
        "COMBATANTS: Let a Blue Queen Ant die",
        "COMBATANTS: Vanquish 20 total Red Ants",
      ],
      quibblerace: [
        "QUIBBLE RACE: Bet for your sponsored Quibble and win the round",
        "QUIBBLE RACE: Gold disk",
        "QUIBBLE RACE: Have $1000+",
        "QUIBBLE RACE: Train a Quibble to have 70+ speed",
        "QUIBBLE RACE: Watch 2 Quibbles die",
      ],
      seasidedrive: [
        "SEASIDE DRIVE: Clear a stage deathless",
        "SEASIDE DRIVE: Clear Stage 1",
        "SEASIDE DRIVE: Clear Stage 1 without your shot charging down to gray",
        "SEASIDE DRIVE: Clear Stage 2",
        "SEASIDE DRIVE: Reach 50,000+ points",
      ],
      campanella3: [
        "CAMPANELLA 3: Beat Galbrain (Stage A)",
        "CAMPANELLA 3: Beat Robopoke (Stage B)",
        "CAMPANELLA 3: Clear 2 waves 0%",
        "CAMPANELLA 3: Clear 2 waves 100%",
        "CAMPANELLA 3: Win the bonus game",
      ],
      cyberowls: [
        "CYBER OWLS: Clear any 2 Rescue Missions using GETM-EOUT",
        "CYBER OWLS: Clear Chicago",
        "CYBER OWLS: Clear Congo",
        "CYBER OWLS: Clear Hong Kong",
        "CYBER OWLS: Clear Moscow",
      ],
    },
    general: {
      general: [
        "Free tile, click first to claim",
        "Beat 1 level/scenario in 3 different epic play games",
        "Buy an item from a shop in 5 different games",
        "Collect 2 gold disks",
        "Collect 5 gifts for the garden",
        "Collect a beverage in 3 different games",
        "Collect a cherry disk",
        "Collect a food item in 3 different games",
        "Crash a vehicle in 4 different games",
        "Defeat 3 bosses",
        "Defeat a boss in 3 different games",
        "Die in 10 different games",
        "Enter a name on 5 arcade leaderboards",
        "Enter a top 3 score on an arcade leaderboard",
        "Enter a top 5 score on 3 arcade leaderboards",
        "Fall into a (non-water) pit in 3 different games",
        "Find an easter egg UFO",
        "Find an egg in 4 games",
        "Get an extra life in 3 different games",
        "Go underwater in 3 different games",
        "Have an exact 50 of anything in 8 games (points, score, and in-game timers count too)",
        "Increase your max HP in 3 games",
        "Jump in 8 games",
        "Kill an enemy in 12 different games",
        "See a bird in 3 different games",
      ],
    },
  },
  tokens: {},
  category_counts: {
    medium: 20,
    general: 5,
  },
} as const;
