export const CAMPANELLA3_UFO = {
  goals: {
    medium: {
      aliens: ["ALIENS: Score 100+", "ALIENS: Score 75+"],
      arena: ["ARENA: Score 20+", "ARENA: Score 40+"],
      pushem: ["PUSHEM: Score 80+", "PUSHEM: Soft lock the game"],
      bats: ["BATS: Score 100+", "BATS: Score 150+"],
      bird: ["BIRD: Score 20+", "BIRD: Score 40+"],
      bopper: ["BOPPER: Score 50+", "BOPPER: Score 80+"],
      boss: ["BOSS: Break 4 yellow blocks"],
      boss2: ["BOSS2: Destroy the 4 red barriers that protect the orb"],
      bouncy: ["BOUNCY: Catch 5 yellow rocks in a row", "BOUNCY: Score 300+"],
      bricks: ["BRICKS: Destroy 3 gold blocks in one run", "BRICKS: Score 15+"],
      cherry: ["CHERRY: Score 130+", "CHERRY: Score 90+"],
      coins: ["COINS: Score 123+", "COINS: Score 69+"],
      crowd: ["CROWD: Score 50+", "CROWD: Score 75+"],
      defend: ["DEFEND: Score 40+", "DEFEND: Score 60+"],
      dodge: ["DODGE: Score 100+", "DODGE: Score 150+"],
      dodge2: ["DODGE2: Score 100+", "DODGE2: Score 50+"],
      drops: ["DROPS: Score 10+", "DROPS: Score 20+"],
      duel: ["DUEL: Score 50+", "DUEL: Score 70+"],
      eyespy: [
        "EYESPY: Collect 4 apples before the eyes opens twice",
        "EYESPY: Score 150+",
      ],
      find: ["FIND: Find the face on a first reveal", "FIND: Score 250+"],
      fishin: ["FISHIN: Catch a red fish", "FISHIN: Score 12+"],
      hearts: ["HEARTS: Reveal 10 hearts in a row", "HEARTS: Score 80+"],
      hopper: ["HOPPER: Score 50+", "HOPPER: Score 80+"],
      juggle: ["JUGGLE: Score 120+", "JUGGLE: Score 60+"],
      mashit: ["MASHIT: Score 100+", "MASHIT: Score 75+"],
      melt: ["MELT: Melt all of the bricks", "MELT: Score 300+"],
      mimic: ["MIMIC: Score 100+", "MIMIC: Score 60+"],
      mines: ["MINES: Score 25+", "MINES: Score 50+"],
      "more?": ["MORE?: Score 100+", "MORE?: Score 60+"],
      mugs: ["MUGS: Score 130+", "MUGS: Score 80+"],
      obey: ["OBEY: Score 50+", "OBEY: Score 75+"],
      plats: ["PLATS: Score 100+", "PLATS: Score 200+"],
      pool: ["POOL: Score 50+", "POOL: Score 80+"],
      racing: ["RACING: Score 25+", "RACING: Score 35+"],
      rungun: ["RUNGUN: Score 100+", "RUNGUN: Score 60+"],
      search: ["SEARCH: Score 50+", "SEARCH: Score 70+"],
      skater: ["SKATER: Score 30+", "SKATER: Score 50+"],
      sniper: ["SNIPER: Score 15+", "SNIPER: Score 30+"],
      step: ["STEP: Score 160+", "STEP: Score 220+"],
      stopem: ["STOPEM: Score 100+", "STOPEM: Score 50+"],
      strike: ["STRIKE: Get 3 strikes before bouncing", "STRIKE: Score 100+"],
      sword: ["SWORD: Score 100+", "SWORD: Score 150+"],
      sword2: [
        "SWORD2: Destroy half of the yellow barriers",
        "SWORD2: Score 100+",
      ],
      telemi: ["TELEMI: Score 40+", "TELEMI: Score 70+"],
      telepo: ["TELEPO: Score 20+", "TELEPO: Score 40+"],
      tunnel: ["TUNNEL: Score 40+"],
      turret: ["TURRET: Score 100+", "TURRET: Score 50+"],
      wanted: ["WANTED: Score 40+", "WANTED: Score 60+"],
      WEEDS: ["WEEDS: Score 100+", "WEEDS: Score 60+"],
    },
    general: {
      general: [
        "Defeat Galbrain",
        "Have a total score containing 420",
        "Have a total score containing 69",
        "Reach a total score of 10,000+",
      ],
    },
  },
  tokens: {},
  category_counts: {
    medium: 23,
    general: 2,
  },
};
