export const CHERRY_RACE_UFO = {
  goals: {
    A: {
      "(A) Barbuta": ["(A) Barbuta"],
      "(A) Magic Garden": ["(A) Magic Garden"],
      "(A) Velgress": ["(A) Velgress"],
      "(A) Bushido Ball": ["(A) Bushido Ball"],
      "(A) Waldorf's Journey": ["(A) Waldorf's Journey"],
      "(A) Hot Foot": ["(A) Hot Foot"],
      "(A) Pingolf": ["(A) Pingolf"],
      "(A) Mortol II": ["(A) Mortol II"],
      "(A) Overbold": ["(A) Overbold"],
      "(A) Quibble Race": ["(A) Quibble Race"],
    },
    B: {
      "(B) Star Waspir": ["(B) Star Waspir"],
      "(B) The Big Bell Race": ["(B) The Big Bell Race"],
      "(B) Valbrace": ["(B) Valbrace"],
      "(B) Rakshasa": ["(B) Rakshasa"],
      "(B) Night Manor": ["(B) Night Manor"],
      "(B) Devilition": ["(B) Devilition"],
      "(B) Kick Club": ["(B) Kick Club"],
      "(B) Hyper Contender": ["(B) Hyper Contender"],
      "(B) Onion Delivery": ["(B) Onion Delivery"],
      "(B) Fist Hell": ["(B) Fist Hell"],
      "(B) Camouflage": ["(B) Camouflage"],
      "(B) Caramel Caramel": ["(B) Caramel Caramel"],
    },
    C: {
      "(C) Bug Hunter": ["(C) Bug Hunter"],
      "(C) Planet Zoldath": ["(C) Planet Zoldath"],
      "(C) Mooncat": ["(C) Mooncat"],
      "(C) Campanella": ["(C) Campanella"],
      "(C) Campanella 2": ["(C) Campanella 2"],
      "(C) Elfazar's Hat": ["(C) Elfazar's Hat"],
      "(C) Seaside Drive": ["(C) Seaside Drive"],
      "(C) Campanella 3": ["(C) Campanella 3"],
      "(C) Paint Chase": ["(C) Paint Chase"],
      "(C) Mortol": ["(C) Mortol"],
      "(C) Ninpek": ["(C) Ninpek"],
      "(C) Party House": ["(C) Party House"],
      "(C) Rail Heist": ["(C) Rail Heist"],
      "(C) Mini & Max": ["(C) Mini & Max"],
      "(C) Cyber Owls": ["(C) Cyber Owls"],
    },
  },
  tokens: {},
  category_counts: {
    A: 6,
    B: 7,
    C: 12,
  },
} as const;
