export const CHOCO_UFO = {
  goals: {
    easy: {
      carmelcarmel: ["Carmel Carmel: Take a picture of 2 donuts."],
      mortol2: ["Mortol 2: Defeat a fly using the base turrets."],
      waldorf: ["Waldorf: Talk to a penguin."],
      barbuta: ["Barbuta: Kill a mushroom and a bat."],
      bughunter: ["Bug Hunter: Reach half the quota for a job."],
      ninpek: ["Ninpek: Get 2000 points."],
      paintchase: ["Paint Chase: Defeat an enemy with speed from a boost pad."],
      magicgarden: ["Magic Garden: Jump over the same enemy 3 times."],
      mortol: ["Mortol: Defeat an enemy with arrow, stone, and explosion."],
      velgress: ["Velgress: Survive 3 (non-floor) hits."],
      planetzoldath: ["Planet Zoldath: Collect 2 useable items."],
      attactics: ["Attactics: Get a unit to 2 stars."],
      devilition: ["Devilition: Defeat 3 enemies with orange frogs."],
      kickclub: ["Kick Club: Beat a level after summoning the ref."],
      avianos: ["Avianos: Position a unit on a mountain."],
      mooncat: ["Mooncat: Land on 5 clouds in the starting room."],
      bushidoball: ["Bushido Ball: Win a point as Chiyome."],
      blockkoala: ["Block Koala: Make a smiley face in a custom level."],
      camouflage: [
        "Camouflage: Turn into every color in level 1. (log included.).",
      ],
      campanella: ["Campanella: Enter a warp."],
      golfaria: ["Golfaria: Leave the starting cave."],
      thebigbellrace: [
        "The Big Bell Race: Hit 3 different enemies into a wall.",
      ],
      warptank: ["Warptank: Complete a level without hitting any checkpoints."],
      porgy: ["Porgy: Read the entire opening cutscene out loud."],
      oniondelivery: ["Onion Delivery: Get the Quartin Heights time box."],
      partyhouse: ["Party House: Have 10$ at once."],
      hotfoot: ["Hot Foot: Hit an enemy with mascots’ special."],
      divers: ["Divers: Die to a piranha."],
      railheist: ["Rail Heist: Throw a money crate off the train."],
      vainger: ["Vainger: Die to hot room damage."],
      rockonisland: [
        "Rock On! Island: Complete a round while cooking a chicken with 4 campfires at once.",
      ],
      pingolf: ["Pingolf: Hit 3 bumpers."],
      fisthell: ["Fist Hell: Hit an enemy with their own molotov."],
      overbold: ["Overbold: Fill in a lava pit."],
      campanella2: [
        "Campanella 2: Kill every non-respawning enemy in the Burrows 1 exit.",
      ],
      hypercontender: [
        "Hyper Contender: Make your opponent have 0 rings while playing as Donkus.",
      ],
      valbrace: ["Valbrace: Kill a mimic."],
      rakshasa: ["Rakshasa: Find a green egg."],
      starwaspir: ["Star Waspir: Free space click this fast lol."],
      grimstone: ["Grimstone: Win a battle with Rufus alive."],
      lordsofdiskonia: ["Lords of Diskonia: Have 20+ gold."],
      nightmanor: [
        "Night Manor: Die to the killer in the starting room (with the dirty bed.).",
      ],
      elfazarshat: ["Elfazars Hat: Collect a ticket."],
      pilotquest: [
        "Pilot Quest: hit every npc in the starting area with a yoyo. (tree included.)",
      ],
      miniandmax: ["Mini And Max: Enter the train."],
      combatants: [
        "Combatants: Have 3 friendly ants on screen at once. (not counting your character.)",
      ],
      quibblerace: [
        "Quibble Race: Use terminal code BLAK-LITE to watch a race. Scream the name of the winner.",
      ],
      seasidedrive: ["Seaside Drive: Get to 1500+ points."],
      campanella3: [
        "Campanella 3: Get over 70 on a wave without firing forward.",
      ],
      cyberowls: ["Cyber Owls: Eat 2 Dim Sum"],
    },
    medium: {
      carmelcarmel: ["Carmel Carmel: Take a picture of 4 background objects."],
      mortol2: ["Mortol 2: Defeat a mini boss."],
      waldorf: ["Waldorf: Have exactly 0 shells."],
      barbuta: ["Barbuta: Get the Blood Sword."],
      bughunter: ["Bug Hunter: Land on 3 enemies."],
      ninpek: ["Ninpek: Kill 12 enemies as a ghost."],
      paintchase: ["Paint Chase: Figure out who is the best programmer."],
      magicgarden: ["Magic Garden: Jump over a potion without collecting it."],
      mortol: [
        "Mortol: Hold down a switch without using stone. (OPEN-TOMB terminal code allowed.)",
      ],
      velgress: ["Velgress: Collect a key."],
      planetzoldath: ["Planet Zoldath: Make a successful trade."],
      attactics: ["Attactics: Win 2 rounds in ranked mode."],
      devilition: ["Devilition: Kill 3 Villagers in one run."],
      kickclub: ["Kick Club: Find a hidden dessert."],
      avianos: ["Avianos: Get a blessing."],
      mooncat: ["Mooncat: Defeat 3 non-respawning enemies."],
      bushidoball: ["Bushido Ball: Win 2 points as Chiyome."],
      blockkoala: ["Block Koala: Make an amogus in a custom level."],
      camouflage: ["Camouflage: Beat level 1 with all collectables."],
      campanella: [
        "Campanella: Destroy all objects/enemies and collect the coffee on 2 levels.",
      ],
      golfaria: ["Golfaria: Get stuck on sand."],
      thebigbellrace: ["The Big Bell Race: Complete 4 laps without dying."],
      warptank: ["Warptank: Beat a level after collecting a coffee."],
      porgy: ["Porgy: Get a fuel tank."],
      oniondelivery: ["Onion Delivery: Drop off 3 onions."],
      partyhouse: [
        "Party House: Have 3 trouble in one party without getting busted.",
      ],
      hotfoot: ["Hot Foot: Jump over 2 beanbags."],
      divers: ["Divers: Escape a piranha."],
      railheist: ["Rail Heist: Get shot by 3 lawmen."],
      vainger: ["Vainger: Get a game over."],
      rockonisland: ["Rock On! Island: Complete 2 rounds."],
      pingolf: ["Pingolf: Complete 3 holes."],
      fisthell: ["Fist Hell: Get to wave 3 in the gym."],
      overbold: ["Overbold: Have 500 gold at once."],
      campanella2: ["Campanella 2: Have 300+ coins."],
      hypercontender: ["Hyper Contender: Win 1 round as donkus."],
      valbrace: ["Valbrace: Finish the tutorial floor."],
      rakshasa: ["Rakshasa: Get to 3 skulls."],
      starwaspir: ["Star Waspir: Collect GGG EEE GEG and EGG without dying."],
      grimstone: ["Grimstone: Get any party member to level 2."],
      lordsofdiskonia: ["Lords of Diskonia: Have 25+ gold."],
      nightmanor: ["Night Manor: Collect 5 pages."],
      elfazarshat: ["Elfazars Hat: Collect 2 tickets."],
      pilotquest: ["Pilot Quest: Plant 2 seeds."],
      miniandmax: ["Mini And Max: Talk to a spider."],
      combatants: ["Combatants: Feed your queen 5 peas."],
      quibblerace: ["Quibble Race: Win a bet."],
      seasidedrive: ["Seaside Drive: Drive under a car without dying."],
      campanella3: ["Campanella 3: Get 0 on a wave without dying."],
      cyberowls: ["Cyber Owls: Collect the keys in Chicago."],
    },
    hard: {
      carmelcarmel: ["Carmel Carmel: Take a picture of 6 background objects."],
      mortol2: ["Mortol 2: Press a switch."],
      waldorf: ["Waldorf: Have 20 or more shells."],
      barbuta: [
        "Barbuta: Get the Umbrella and get hit by 3 different acid sources.",
      ],
      bughunter: ["Bug Hunter: Make 5 enemies explode."],
      ninpek: ["Ninpek: Pop a 1 up balloon."],
      paintchase: ["Paint Chase: Complete level 3."],
      magicgarden: ["Magic Garden: Jump over a mushroom without dying."],
      mortol: ["Mortol: Defeat 2 alligators."],
      velgress: ["Velgress: Collect 2 keys."],
      planetzoldath: ["Planet Zoldath: Max out your health (7 squares.)"],
      attactics: ["Attactics: Complete 2 campaign stages."],
      devilition: ["Devilition: Kill 4 Villagers in one run."],
      kickclub: ["Kick Club: Complete 1-5"],
      avianos: ["Avianos: Get 50+ seeds."],
      mooncat: ["Mooncat: Enter a portal."],
      bushidoball: ["Bushido Ball: Win 3 points as Chiyome."],
      blockkoala: ["Block Koala: Read the entire intro cutscene out loud."],
      camouflage: ["Camouflage: Beat 2 levels with all collectables."],
      campanella: ["Campanella: Make the cat appear. (Do nothing.)"],
      golfaria: ["Golfaria: Touch an eagle."],
      thebigbellrace: ["The Big Bell Race: Complete 6 laps without dying."],
      warptank: ["Warptank: Beat 2 levels."],
      porgy: ["Porgy: Get 3 fuel tanks."],
      oniondelivery: ["Onion Delivery: Drop off 5 onions."],
      partyhouse: ["Party House: Buy a star guest."],
      hotfoot: ["Hot Foot: Get a blow out."],
      divers: ["Divers: Pull a lever."],
      railheist: ["Rail Heist: Get 1 pacifist and 1 devil star."],
      vainger: ["Vainger: Get a shield upgrade."],
      rockonisland: ["Rock On! Island: Complete 3 rounds."],
      pingolf: ["Pingolf: Complete 4 holes."],
      fisthell: ["Fist Hell: Defeat the campanella and grab its loot."],
      overbold: ["Overbold: Have 600 gold at once."],
      campanella2: ["Campanella 2: Break the orb in Burrows 2."],
      hypercontender: ["Hyper Contender: Win 2 rounds as donkus."],
      valbrace: ["Valbrace: Finish the first (non tutorial) floor."],
      rakshasa: ["Rakshasa: Get to 4 skulls."],
      starwaspir: ["Star Waspir: Get a 10x multiplier."],
      grimstone: ["Grimstone: Enter the village to the north of spawn."],
      lordsofdiskonia: ["Lords of Diskonia: Have 30+ gold."],
      nightmanor: ["Night Manor: Collect 7 pages."],
      elfazarshat: ["Elfazars Hat: Defeat the tree mini boss."],
      pilotquest: ["Pilot Quest: Plant 3 seeds."],
      miniandmax: ["Mini And Max: Talk to an algean."],
      combatants: ["Combatants: Complete first blood."],
      quibblerace: ["Quibble Race: Win a race after buying steroids."],
      seasidedrive: ["Seaside Drive: Get 2500+ points."],
      campanella3: ["Campanella 3: Get 0 on 2 waves without dying."],
      cyberowls: ["Cyber Owls: See the dim sum truck in Hong Kong."],
    },
    veryhard: {
      carmelcarmel: ["Carmel Carmel: Let a mini boss escape."],
      mortol2: ["Mortol 2: Defeat 2 minibosses."],
      waldorf: ["Waldorf: Have 30 or more shells."],
      barbuta: ["Barbuta: Get the candy"],
      bughunter: ["Bug Hunter: Complete a job."],
      ninpek: ["Ninpek: Use HARD-LOOP and get 2000+ points without dying."],
      paintchase: ["Paint Chase: Complete level 4."],
      magicgarden: ["Magic Garden: Drop off 60+ oppies."],
      mortol: ["Mortol: Complete 1-2."],
      velgress: ["Velgress: Get to level 3."],
      planetzoldath: ["Planet Zoldath: Get a map piece."],
      attactics: ["Attactics: Win 4 ranked games."],
      devilition: ["Devilition: Use terminal code FULL-RAND beat round 4."],
      kickclub: ["Kick Club: Complete 1-8"],
      avianos: ["Avianos: Get 70+ seeds."],
      mooncat: ["Mooncat: See 6 screens."],
      bushidoball: ["Bushido Ball: Win 4 points as Chiyome."],
      blockkoala: [
        "Block Koala: Use every tile in a custom level and then beat it.",
      ],
      camouflage: ["Camouflage: Beat 3 levels with all collectables."],
      campanella: [
        "Campanella: Enter the bonus stage with 0 score. (No warps allowed.) Get 2000+ score in the bonus stage.",
      ],
      golfaria: ["Golfaria: Get a stroke upgrade."],
      thebigbellrace: ["The Big Bell Race: Win a race."],
      warptank: ["Warptank: Beat 3 levels."],
      porgy: ["Porgy: Get 4 fuel tanks."],
      oniondelivery: [
        "Onion Delivery: Drop off 7 onions and complete the day.",
      ],
      partyhouse: ["Party House: Use cupid to boot out 2 trouble at once."],
      hotfoot: ["Hot Foot: Get 2 blow outs"],
      divers: ["Divers: Open 2 chests."],
      railheist: ["Rail Heist: Get 2 pacifists and 1 devil star."],
      vainger: ["Vainger: Get the heat mod."],
      rockonisland: [
        "Rock On! Island: Complete 3 rounds without buying any cavemen.",
      ],
      pingolf: ["Pingolf: Complete 6 holes."],
      fisthell: ["Fist Hell: Complete the First Scare."],
      overbold: ["Overbold: Have 800 gold at once."],
      campanella2: ["Campanella 2: Have 400+ gold."],
      hypercontender: [
        "Hyper Contender: Win 2 rounds as donkus. Win 1 round on draft mode.",
      ],
      valbrace: ["Valbrace: Give the red knight 3 items."],
      rakshasa: ["Rakshasa: Defeat the bridge troll."],
      starwaspir: ["Star Waspir: Get a 15x multiplier."],
      grimstone: ["Grimstone: Enter the church south of spawn."],
      lordsofdiskonia: [
        "Lords of Diskonia: In full war have a full squad. (no empty spaces.)",
      ],
      nightmanor: ["Night Manor: Collect 8 pages and say Slenderman out loud."],
      elfazarshat: ["Elfazars Hat: Complete the first level."],
      pilotquest: ["Pilot Quest: Plant 4 seeds."],
      miniandmax: ["Mini And Max: Talk to a Lampian."],
      combatants: ["Combatants: Complete 2 levels."],
      quibblerace: ["Quibble Race: Win a race after buying poison."],
      seasidedrive: ["Seaside Drive: Get 3000+ points."],
      campanella3: ["Campanella 3: Get 0 on 3 waves without dying."],
      cyberowls: ["Cyber Owls: In Moscow break a wall with a grenade."],
    },
    general: {
      general: [
        "Meow: Party House: Wake up the cat. Magic Garden: spawn a potion.",
        "Potty Mouth: Write the name ASS into 2 arcade leaderboards.",
        "PewDiePie: Stand on a bridge in Golfaria and Rakshasa.",
        "Rougelikes: Campanella 2: Beat Burrows 1. Velgress: Beat the first stage.",
        "Toadally Radical: Devilition: Fully clear (all demons dead) a round by killing the final demon with a toad. Camouflage: Get eaten by a frog.",
        "Evil Pilot: Big Bell Race: As Pilot kill the same racer twice. Campanella 3: Get 100 on a wave.",
        "Hunger: Combatants: Feed your queen 3 peas. Fist Hell: Eat food from the trash.",
        "Wave Clearer: Overbold: Clear 1 wave. Fist Hell: Clear 1 wave in the gym.",
        "Tactics: Attactics: Beat First Encounter. Avianos: Control 5 tiles at once.",
        "Classic: Barbuta: Kill a mushroom. Mooncat: Kill a mushroom.",
        "Pretty In Pink?: Mortol: Defeat all enemies that come out of 1 arrow trap. Campanella 2: Defeat 3 blue guys that pop out of tubes.",
        "Sequence Break: Porgy: Use CHAN-DAR! and kill a boss. Pilot Quest: Use MORE-MEAT and kill any boss.",
        "Cats Cats Cats Cats: Find a cat in 4 games.",
        "Infant Rush: Talk to a baby in Rock On! Island and drop off an egg to its mom in Porgy.",
        "Double Barrel: Destroy a barrel in Campanella 2 and Cyber Owls.",
        "Fighting Spirit: Ninpek: Defeat 3 enemies as a ghost. Rakshasa: revive 3 times in one run.",
        "Tiger Woods: Pingolf: Get a hole in 1. Golfaria: Get a Stroke upgrade.",
        "Futurama: Pilot the Campanella/Big Belle in 5 games.",
        "Knucklehead: Waldorf: Knock a pig into the sea. Golfaria: Knock an enemy into a pit or water.",
        "Trolls Don’t Get Blocked: Block Koala: Beat a level. Rail Heist: Stop a lawman from climbing a ladder by placing a block on either end.",
        "Let Me In: Collect a key in 3 games.",
        "Trickshot: Night Manor: Use OPEN-CAGE hit the killer with a hook and yell NOSCOPE.",
        "Slick: Onion Delivery: Jump off 5 different ramps. Kick Club: Beat a level by hitting 2 or more enemies with a charged shot.",
        "Ballin’: Bushido Ball: Win 1 round. Hot Foot: Win 1 game.",
        "Healthy: Vainger: Get a Shield upgrade. Planet Zoldath: Get a health upgrade.",
        "Lil Buddy: View An Animate And Inanimate gift in the garden.",
        "Scoring: Magic Garden: Get 3x score. Star Waspir: Get 8x score.",
        "Code Red: Campanella: Use BEAN-DRIP score 1300+ points. Seaside Drive: Use WEAK-SHOT and get 1500+ points. ",
        "EWWWW: Bug Hunter: Stomp on a bug. Mini And Max: Kill 3 different types of bugs.",
        "Eye Don’t Know: Warptank: Use SLIM-TANK and beat Stare Sector. Caramel Caramel: Use TEST-LENS to take a picture of 10 or more ghosts.",
        "Just A Game: Hot Foot: Knock an enemy over. Bushido Ball: Hit an enemy in 2 separate rounds.",
        "Sharpshooter: Mortol 2: Defeat 5 enemies as gunner. Cyber Owls: In Congo defeat an enemy with their own grenade.",
        "Drunkard: Magic Garden: Drink a potion. Valbrace: Drink a red potion.",
        "Lil Buddy 2: Get 2 Appliances/Electronic Gifts And View Them In The Garden.",
        "Pretty Colors: Camouflage: Beat level 1. Paint Chase: Beat level 1.",
        "Save The Animals: Grimstone: Use WOLF-PACK and win a fight. Fist Hell: Unleash a dog.",
        "Bonus Round: Elfazars Hat: Use SIDE-SHOW and collect 5 coins. Hyper Contender: Use PAST-RULE and win 1 tournament round.",
        "Let’s Go Gambling: Quibble Race: win a 2:1 bet or higher. Overbold: Win a 300 or higher round.",
        "Popular: Party House: Get to 10 pop. Rock On! Island: Talk to everyone in Village of Peace.",
        "RPG: Grimstone: Get any character to level 2. Divers: Get to level 2.",
      ],
    },
  },
  tokens: {},
  category_counts: {
    easy: 5,
    medium: 5,
    hard: 5,
    veryhard: 5,
    general: 5,
  },
} as const;
