export const NOZZLO_UFO = {
  goals: {
    medium: {
      barbuta: [
        "BARBUTA: Buy 7 eggs in one run",
        "BARBUTA: Cherry the game without praying at the altar",
        "BARBUTA: Kill the mimic, unlock the door, hammer the wall, and save the castle in one run",
        "BARBUTA: Save the castle without hitting any creatures with a sword",
        "BARBUTA: Visit 63+ rooms total",
      ],
      bughunter: [
        "BUG HUNTER: Beat the first 6 jobs in a row",
        "BUG HUNTER: Complete 2 jobs in a row without using an attack module",
        "BUG HUNTER: Use all 41 modules",
        "BUG HUNTER: Using ACES-SHOP, complete job 4",
        "BUG HUNTER: Using WORK-LESS, complete jobs 13, 14, and 15 in a row",
      ],
      ninpek: [
        "NINPEK: Cherry Disk",
        "NINPEK: Eat 28+ sandwiches in one run (stats page has it if your memory flubs it)",
        "NINPEK: Gold Disk without dying",
        "NINPEK: Reach 60,000+ points",
        "NINPEK: Using HARD-LOOP, win with 8+ lives",
      ],
      paintchase: [
        "PAINT CHASE: Beat each level without crashing (EVEN-COAT allowed for up to 3 levels)",
        "PAINT CHASE: Beat the game with UNDER 120 points",
        "PAINT CHASE: Cherry Disk",
        "PAINT CHASE: Have 8 lives",
        "PAINT CHASE: Using EVEN-COAT, get a perfect score on 15 levels",
      ],
      magicgarden: [
        "MAGIC GARDEN: Cherry disk, but save exactly 1 oppy at a time",
        "MAGIC GARDEN: Kill 25 mushrooms in one run",
        "MAGIC GARDEN: Reach a score of 750,000+",
        "MAGIC GARDEN: Save 212+ oppies in one run",
        "MAGIC GARDEN: Win 5 games in a row",
      ],
      mortol: [
        "MORTOL: Cherry Disk",
        "MORTOL: Have a total of 200 lives on the map",
        "MORTOL: Using BENS-MODE, beat the game",
        "MORTOL: Using FIRE-ARRO, beat the game",
        "MORTOL: Using LEAF-HEAD, beat the game",
      ],
      velgress: [
        "VELGRESS: Cherry 3 attempts in a row",
        "VELGRESS: Cherry disk (No star pads/no upgrades)",
        "VELGRESS: Cherry the game with 120+ coins",
        "VELGRESS: Gold disk (No star pads/no upgrades/no shooting)",
        "VELGRESS: Win 5 attempts in a row",
      ],
      planetzoldath: [
        "PLANET ZOLDATH: Carry 63 of each resource at once",
        "PLANET ZOLDATH: Cherry Disk",
        "PLANET ZOLDATH: Die after collecting all 3 map parts. Stupid Pilot!",
        "PLANET ZOLDATH: Gather 8 tools on the floor of the backmost dungeon room",
        "PLANET ZOLDATH: Gold Disk without collecting energy cubes",
      ],
      attactics: [
        "ATTACTICS: Gold Disk",
        "ATTACTICS: Reach Emperor in ranked mode",
        "ATTACTICS: Score 8000+ points in Survival Mode",
        "ATTACTICS: Using SLOW-DOWN with 1 move per turn, get 5000+ points on Survival Mode",
        "ATTACTICS: Using SLOW-DOWN, beat a Rank 300 challenge",
      ],
      devilition: [
        "DEVILITION: Beat the game with 0 pieces left to place at the end of every round",
        "DEVILITION: Beat the game with 11 townies",
        "DEVILITION: Beat the game with 50,000 points",
        "DEVILITION: Using FULL-RAND, beat the game in under 13 minutes",
        "DEVILITION: Using WEAK-TOWN, beat the game",
      ],
      kickclub: [
        "KICK CLUB: Beat 20 levels in one run without picking up the ball (using headbonks and slides)",
        "KICK CLUB: Beat Ice World without ever letting the ball go dim",
        "KICK CLUB: Beat USA World entering it with no extra lives, as the girl character",
        "KICK CLUB: Eat at least 30 hidden sweets in one run. Yummy!",
        "KICK CLUB: Score 200,000 points",
      ],
      avianos: [
        "AVIANOS: Cherry Disk",
        "AVIANOS: Max out blessings from all Ancestors in a Trial and then win",
        "AVIANOS: Win an Adult game while holding all 6 castles",
        "AVIANOS: Win Trial 4 while only using 3 ancestors",
        "AVIANOS: Win Trials 1-3 while only creating 1 type of troop",
      ],
      mooncat: [
        "MOONCAT: Cherry Disk",
        "MOONCAT: Collect an egg without dying",
        "MOONCAT: Collect an egg without stomping on any non-boss enemy",
        "MOONCAT: Collect an egg, then change P1 Input and collect a different egg",
        "MOONCAT: Visit all 42 different rooms",
      ],
      bushidoball: [
        "BUSHIDO BALL: Cherry Disk with default settings with 3 characters",
        "BUSHIDO BALL: Gold Disk with default settings EXCEPT 20 goals to win",
        "BUSHIDO BALL: Gold Disk with default settings EXCEPT hyper speed",
        "BUSHIDO BALL: Gold Disk with default settings with all 6 characters",
        "BUSHIDO BALL: Gold Disk with default settings without winning a match where your opponent scores",
      ],
      blockkoala: [
        "BLOCK KOALA: Beat 15 levels with Koala Kid and 15 different levels with Koalarana",
        "BLOCK KOALA: Beat any 20 story levels without using undos",
        "BLOCK KOALA: Gold Disk with the music on",
        "BLOCK KOALA: Talk to all 20 worms without using WORM-1234",
        "BLOCK KOALA: Using WORM-1234, clear levels 31-50",
      ],
      camouflage: [
        "CAMOUFLAGE: Cherry Disk",
        "CAMOUFLAGE: Cherry Disk in only 70 camouflages (sum of best in each stage)",
        "CAMOUFLAGE: Get eaten by Bird in 11 different levels",
        "CAMOUFLAGE: Gold Disk in only 25 camouflages (sum of best in each stage on your path)",
        "CAMOUFLAGE: Gold Disk with 0 deaths",
      ],
      campanella: [
        "CAMPANELLA: Cherry Disk",
        "CAMPANELLA: Gold Disk without dying",
        "CAMPANELLA: Have 50 lives",
        "CAMPANELLA: Win with 2000 or less points",
        "CAMPANELLA: Win with 67,000+ points",
      ],
      golfaria: [
        "GOLFARIA: Collect 20 clubs",
        "GOLFARIA: Destroy 10 parbots",
        "GOLFARIA: Gold Disk in under 600 strokes",
        "GOLFARIA: Gold Disk without resetting or running out of strokes",
        "GOLFARIA: Rescue 8 green balls",
      ],
      thebigbellrace: [
        "THE BIG BELL RACE: Cherry Disk but make sure Pilot gets 20 or less points",
        "THE BIG BELL RACE: Cherry Disk while always giving all other racers a 1 lap head start",
        "THE BIG BELL RACE: Cherry Disk without collecting powerups",
        "THE BIG BELL RACE: Gold disk while KOing other racers 25 times",
        "THE BIG BELL RACE: Gold disk without taking damage",
      ],
      warptank: [
        "WARPTANK: Beat 20 levels with a sum of best times of  under 18 minutes",
        "WARPTANK: Clear the Special Stage",
        "WARPTANK: Defeat Big Tank",
        "WARPTANK: Defeat Renegade",
        "WARPTANK: Gold Disk but reset the game each time you die",
      ],
      waldorfsjourney: [
        "WALDORF’S JOURNEY: Cherry Disk two attempts in a row",
        "WALDORF’S JOURNEY: Gold Disk without flying",
        "WALDORF’S JOURNEY: Have 110 shells at once",
        "WALDORF’S JOURNEY: Read all 22 signs",
        "WALDORF’S JOURNEY: Win 5 times in a row",
      ],
      porgy: [
        "PORGY: Collect 20 fuel tanks",
        "PORGY: Collect 20 torpedo upgrades",
        "PORGY: Collect all 10 equipable upgrades",
        "PORGY: Defeat 6 bosses with 1 or less upgrades equipped during boss fights",
        "PORGY: Return 20 fish eggs to their mother",
      ],
      oniondelivery: [
        "ONION DELIVERY: Cherry Disk",
        "ONION DELIVERY: Complete 3 different-weathered days without taking damage",
        "ONION DELIVERY: Complete the week without a death",
        "ONION DELIVERY: Deliver 4 Onions to Jurli's in one run",
        "ONION DELIVERY: Using ROAD-RAGE, deliver 30 onions in a row without hitting a vehicle or falling in the slime",
      ],
      caramelcaramel: [
        "CARAMEL CARAMEL: Cherry Disk",
        "CARAMEL CARAMEL: Get the no-hit bonus on each of the main 3 planets (can be different runs)",
        "CARAMEL CARAMEL: Gold Disk but hold down the firing button the whole time",
        "CARAMEL CARAMEL: Gold Disk but only kill enemies that have been snapped by the camera",
        "CARAMEL CARAMEL: Photograph at least 30 enemy types in one run",
      ],
      partyhouse: [
        "PARTY HOUSE: Beat 3 different scenarios in a row without ever having 60+ pop or 25+ money",
        "PARTY HOUSE: Beat all 5 main scenarios with 5 days left",
        "PARTY HOUSE: Cherry Disk but reset whenever you have only 2 days left",
        "PARTY HOUSE: Host a random scenario party with 8+ stars at the party",
        "PARTY HOUSE: In a random scenario, get busted 10+ times and win",
      ],
      hotfoot: [
        "HOT FOOT: Cherry Disk",
        "HOT FOOT: Gold Disk with 8 different characters",
        "HOT FOOT: Gold Disk without using special throws or abilities",
        "HOT FOOT: Using LEFT-FOOT, get 5 blowouts in one run",
        "HOT FOOT: Using TEST-BAGS, win a tournament with 7 max bags and a point goal of 30",
      ],
      divers: [
        "DIVERS: Defeat Guelap without ever equipping anything to Thyme",
        "DIVERS: Equip the Thorn Shield, Parasite Hammer, and Holy Rod",
        "DIVERS: Gold Disk",
        "DIVERS: Have a character with 2000 HP",
        "DIVERS: Purchase every Lance, Sledge, and Buckler in the shop at least once",
      ],
      railheist: [
        "RAIL HEIST: Bring back 15 unique intact money crates",
        "RAIL HEIST: Gold Disk",
        "RAIL HEIST: Kill 40 unique chickens",
        "RAIL HEIST: Obtain 15 devil stars without shooting your gun",
        "RAIL HEIST: Use GOOD-SPUR, Obtain 20 angel stars",
      ],
      vainger: [
        "VAINGER: Collect 3 keycode pieces without dying once",
        "VAINGER: Collect 4 Mods, 3 Clones, and 2 Stabilizers",
        "VAINGER: Collect at least 20 shield upgrades",
        "VAINGER: Enter the 4th region without collecting a stabilizer",
        "VAINGER: Gold Disk",
      ],
      rockonisland: [
        "ROCK ON! ISLAND: Beat any 7 main levels damageless",
        "ROCK ON! ISLAND: Beat any 8 main levels without chickens or using your weapon",
        "ROCK ON! ISLAND: Beat any 9 main levels placing less than 20 cavemen total",
        "ROCK ON! ISLAND: Gold Disk",
        "ROCK ON! ISLAND: Using CLUB-PASS, beat The Four Emperors without chickens or using your weapon",
      ],
      pingolf: [
        "PINGOLF: Cherry disk",
        "PINGOLF: Get an exact hole in 2 on 17 holes",
        "PINGOLF: Gold Disk while dunking EVERY shot",
        "PINGOLF: Gold Disk without dunking any shots",
        "PINGOLF: Reach a score of -12",
      ],
      mortolii: [
        "MORTOL II: Cherry Disk while killing all 3 mini-bosses",
        "MORTOL II: Cherry Disk without pressing a switch or unlocking a door",
        "MORTOL II: Cherry Disk without using the scout",
        "MORTOL II: Have 15 keys at the same time",
        "MORTOL II: Using BENE-DIKT, win the game",
      ],
      fisthell: [
        "FIST HELL: Cherry Disk",
        "FIST HELL: Clear wave 20 at the gym",
        "FIST HELL: Gold Disk without punching any enemies",
        "FIST HELL: Have $100 at once",
        "FIST HELL: Win with 3 playable characters",
      ],
      overbold: [
        "OVERBOLD: Buy out the entire shop",
        "OVERBOLD: Gold Disk using only price-hiked upgrades",
        "OVERBOLD: Win 3 runs in a row",
        "OVERBOLD: Win without firing a shot unless the boss is onscreen",
        "OVERBOLD: Win, completing wave 2 with $900 stakes and waves 3-7 with $1600 stakes",
      ],
      campanella2: [
        "CAMPANELLA 2: Cherry Disk",
        "CAMPANELLA 2: Get 10+ upgrades at once (squares under health/fuel count)",
        "CAMPANELLA 2: Gold Disk twice in a row",
        "CAMPANELLA 2: Gold Disk, going through Gut",
        "CAMPANELLA 2: Have 2000 coins",
      ],
      hypercontender: [
        "HYPER CONTENDER: Beat the tournament with all 8 characters",
        "HYPER CONTENDER: Cherry Disk without using rematches",
        "HYPER CONTENDER: Using PAST-RULE, win 8 draft fights in a row",
        "HYPER CONTENDER: Using PAST-RULE, win the tournament with all 8 characters",
        "HYPER CONTENDER: Win a tournament using only melee attacks",
      ],
      valbrace: [
        "VALBRACE: Cherry Disk",
        "VALBRACE: Gold Disk without casting spells",
        "VALBRACE: Have 20+ points in any stat",
        "VALBRACE: Using 4RCH-MAGE, beat the game",
        "VALBRACE: Using BUGG-BODY, beat the game",
      ],
      rakshasa: [
        "RAKSHASA: Beat all 6 minibosses/bosses while having 4+ skulls",
        "RAKSHASA: Cherry Disk without dying (after the beginning)",
        "RAKSHASA: Gold Disk without collecting weapon upgrades",
        "RAKSHASA: Revive yourself 14 times in one run",
        "RAKSHASA: Win with 80,000+ points",
      ],
      starwaspir: [
        "STAR WASPIR: Cherry Disk without letting go of fire",
        "STAR WASPIR: Clear wave 5 with all 3 ships in a row",
        "STAR WASPIR: Have a 50x multiplier",
        "STAR WASPIR: Score 1,000,000 points",
        "STAR WASPIR: Win with 300,000 points with all 3 ships",
      ],
      grimstone: [
        "GRIMSTONE: Defeat Famine",
        "GRIMSTONE: Obtain Abyssidian",
        "GRIMSTONE: Rest in El Pasaje with 3 or less characters in the party",
        "GRIMSTONE: Unlock every train station",
        "GRIMSTONE: Using WOLF-PACK, save Leo from the Black Prison",
      ],
      lordsofdiskonia: [
        "LORDS OF DISKONIA: Gold Disk",
        "LORDS OF DISKONIA: Have 75+ gold",
        "LORDS OF DISKONIA: Kill an enemy using 15 different unit types (Good memory recommended)",
        "LORDS OF DISKONIA: Win 3 Commander difficulty Full Wars in a row",
        "LORDS OF DISKONIA: Win 7 Commander difficulty Quick Battles in a row",
      ],
      nightmanor: [
        "NIGHT MANOR: Cherry Disk without any bad dreams",
        "NIGHT MANOR: Find 17 journal entries without having any bad dreams",
        "NIGHT MANOR: Get the gold and cherry endings",
        "NIGHT MANOR: Make 10 unique loud, killer-attracting noises in a row without getting caught and stabbed",
        "NIGHT MANOR: Using OPEN-CAGE, kill the killer",
      ],
      elfazarshat: [
        "ELFAZAR’S HAT: Beat the game without dying",
        "ELFAZAR’S HAT: Cherry without using any level 2 upgrades (three of a kinds)",
        "ELFAZAR’S HAT: Fill the bonus meter in the bonus minigame thrice in one run",
        "ELFAZAR’S HAT: Gold Disk using only the best two upgrades: BOMB and SHLD",
        "ELFAZAR’S HAT: Gold Disk without spinning",
      ],
      pilotquest: [
        "PILOT QUEST: Activate all the teleporters",
        "PILOT QUEST: Die to Nozzlo, greatest in all the land",
        "PILOT QUEST: Have over 4000 seconds on the clock in the Wild Zone",
        "PILOT QUEST: Obtain the Wizard Yoyo",
        "PILOT QUEST: Plant 6 seeds at the crash site",
      ],
      miniandmax: [
        "MINI & MAX: Cherry Disk",
        "MINI & MAX: Find 7 Big Shinies",
        "MINI & MAX: Gold Disk before 7:20PM (in-game)",
        "MINI & MAX: Gold Disk with only the Magic Potion II and Gravity Charm upgrades (no health ups or energy eggs, either!",
        "MINI & MAX: Obtain 39 upgrades",
      ],
      combatants: [
        "COMBATANTS: Beat 'Commando', 'Surprise!', 'Ambush', and 'Pincered'",
        "COMBATANTS: Beat ‘Open Field’",
        "COMBATANTS: Gold Disk with 0 failed missions",
        "COMBATANTS: Gold Disk without firing your weapon",
        "COMBATANTS: Kill 7 unique spiders (they gotta die to blue forces)",
      ],
      quibblerace: [
        "QUIBBLE RACE: Cherry Disk without any insider info or thug help",
        "QUIBBLE RACE: Have $100,000+",
        "QUIBBLE RACE: Using TUFF-RACE, win a 6 round game with $30,000+",
        "QUIBBLE RACE: Using WILD-BETS, win with $500,000+",
        "QUIBBLE RACE: Win 3 consecutive 6 round games",
      ],
      seasidedrive: [
        "SEASIDE DRIVE: Beat the game while firing exclusively green shots",
        "SEASIDE DRIVE: Beat the game without ever letting your shot charge down to green",
        "SEASIDE DRIVE: Finish the game with 9 lives",
        "SEASIDE DRIVE: Reach 350,000+ points",
        "SEASIDE DRIVE: Using WEAK-SHOT, beat the game",
      ],
      campanella3: [
        "CAMPANELLA 3: Clear 19 waves 100% (can be different runs",
        "CAMPANELLA 3: Clear 20 waves 0% (Can be different runs",
        "CAMPANELLA 3: Gold Disk without dying",
        "CAMPANELLA 3: Win with 2000+ points and using no continues",
        "CAMPANELLA 3: Win with 2500+ points",
      ],
      cyberowls: [
        "CYBER OWLS: Beat Chicago, Moscow, Congo, and Hong Kong without taking any damage",
        "CYBER OWLS: Beat the game with over 12000 points",
        "CYBER OWLS: Cherry Disk",
        "CYBER OWLS: Clear 30 Rescue Missions in a row using GETM-EOUT",
        "CYBER OWLS: Using HAWK-BASE, clear Antarctica without taking any damage",
      ],
      general: [
        "100% Vainger, Golfaria, Warptank, or Porgy",
        "Be the best score on 5 arcade leaderboards",
        "Beat 3 games in co-op (friends optional)",
        "Buy 3 unique items from a shop in 12 different games",
        "Cherry the 4 corners of the Random sort in the library",
        "Collect 10 cherry disks",
        "Collect 15 gold disks",
        "Collect 30 gifts for the garden",
        "Collect a beverage in 9 different games",
        "Collect a food item in 15 different games",
        "Complete every step of the secret hunt that starts in the Night Manor history",
        "Conquer a leaderboard! Get the same name on EVERY entry!",
        "Defeat 30 bosses",
        "Defeat a boss in 20 different games",
        "Die in or lose at all 50 games",
        "Find an egg in 18 games",
        "Get a Gold Disk bingo in the Random sort in the library (5 in a row)",
        "Get a top 3 score on 10 leaderboards",
        "Get Gold Disk on 4 different epic play games",
        "Have an exact number 50 onscreen in 45 games (points, score, and in-game timers count too!)",
        "Increase your max HP in 12 games",
        "Kill something in every game (nonlethal violence permitted in Bushido B./Porgy/Party House/Hotfoot/Hyper C; kill a black block in Block Koala)",
        "See 10 terminal codes in-game (no, inputting them doesn't count)",
        "Spot the Campanella in 12 different games",
        "Trigger 6 secret hidden dev messages (that are not part of the secret scavenger hunt)",
      ],
    },
  },
  tokens: {},
  category_counts: {
    medium: 25,
  },
} as const;
