import { Descriptions, OptionList } from "@/app/generator/ufoGenerator";
import { Game } from "@/app/goals";

export const GOLDS: OptionList = {
  shown: [],
  shown_if_on_card: [
    "nightmanor",
    "mortolii",
    "waldorfsjourney",
    "bushidoball",
    "velgress",
    "mooncat",
    "magicgarden",
    "pingolf",
    "quibblerace",
    "barbuta",
    "camouflage",
    "hotfoot",
    "overbold",
    "hypercontender",
    "starwaspir",
    "ninpek",
    "thebigbellrace",
    "oniondelivery",
    "rakshasa",
    "campanella",
    "caramelcaramel",
    "kickclub",
    "seasidedrive",
    "campanella2",
    "campanella3",
    "fisthell",
    "elfazarshat",
    "planetzoldath",
    "avianos",
    "bughunter",
    "devilition",
  ],
  hidden: [
    "partyhouse",
    "cyberowls",
    "miniandmax",
    "paintchase",
    "mortol",
    "attactics",
    "golfaria",
    "combatants",
    "warptank",
    "railheist",
    "porgy",
    "blockkoala",
    "divers",
    "vainger",
    "rockonisland",
    "valbrace",
    "grimstone",
    "lordsofdiskonia",
    "pilotquest",
  ],
};

export const CHERRIES: OptionList = {
  shown: [],
  shown_if_on_card: [
    "mortolii",
    "bushidoball",
    "waldorfsjourney",
    "velgress",
    "magicgarden",
    "pingolf",
    "barbuta",
    "hotfoot",
    "quibblerace",
    "overbold",
    "nightmanor",
    "starwaspir",
    "thebigbellrace",
    "rakshasa",
    "campanella",
    "kickclub",
    "fisthell",
    "campanella2",
    "caramelcaramel",
    "planetzoldath",
    "elfazarshat",
    "seasidedrive",
    "campanella3",
    "camouflage",
    "mooncat",
    "oniondelivery",
    "hypercontender",
    "devilition",
    "ninpek",
  ],
  hidden: [
    "bughunter",
    "valbrace",
    "paintchase",
    "cyberowls",
    "partyhouse",
    "mortol",
    "avianos",
    "attactics",
    "divers",
    "railheist",
    "vainger",
    "miniandmax",
    "combatants",
    "blockkoala",
    "golfaria",
    "warptank",
    "rockonisland",
    "porgy",
    "grimstone",
    "lordsofdiskonia",
    "pilotquest",
  ],
};

const GIFT_DESCRIPTION_ENTRIES: ReadonlyArray<[Game, string]> = [
  ["magicgarden", "10 opps"],
  ["blockkoala", "Custom"],
  ["pingolf", "Hole-in-one"],
  ["ninpek", "3 sandwiches"],
  ["avianos", "Max blessing"],
  ["mooncat", "1 warp"],
  ["thebigbellrace", "1st"],
  ["waldorfsjourney", "50%"],
  ["divers", "Parasite Hammer"],
  ["rakshasa", "3 revives"],
  ["starwaspir", "10x"],
  ["nightmanor", "Escape"],
  ["cyberowls", "1 rescue"],
  ["bushidoball", "3 rounds"],
  ["mortolii", "Switch"],
  ["quibblerace", "Sponsor"],
  ["velgress", "2 keys"],
  ["valbrace", "Level 8"],
  ["golfaria", "Block Buster"],
  ["vainger", "Heat mod"],
  ["overbold", "Win 500+"],
  ["campanella", "15 lives"],
  ["caramelcaramel", "Egg"],
  ["seasidedrive", "Bonus"],
  ["campanella3", "Bonus"],
  ["oniondelivery", "2 days"],
  ["hotfoot", "3 rounds"],
  ["miniandmax", "100 shinies"],
  ["partyhouse", "1 win"],
  ["elfazarshat", "Bonus"],
  ["bughunter", "1 job"],
  ["fisthell", "9 rounds"],
  ["pilotquest", "Unktomi"],
  ["campanella2", "Bracelet"],
  ["barbuta", "25 rooms"],
  ["camouflage", "30%"],
  ["porgy", "Lamia"],
  ["planetzoldath", "1 Map"],
  ["hypercontender", "Draft"],
  ["kickclub", "Track World"],
  ["combatants", "Spider"],
  ["devilition", "5 lvls"],
  ["paintchase", "12 lvls"],
  ["railheist", "10 lvls"],
  ["mortol", "2-C"],
  ["attactics", "12 lvls"],
  ["grimstone", "10 level ups"],
  ["warptank", "Renegade"],
  ["rockonisland", "Camp"],
  ["lordsofdiskonia", "5 lvls"],
];
export const GIFT_DESCRIPTIONS: Descriptions = Object.fromEntries(
  GIFT_DESCRIPTION_ENTRIES,
);
export const GIFTS: OptionList = {
  shown: [],
  shown_if_on_card: [
    "magicgarden",
    "blockkoala",
    "pingolf",
    "ninpek",
    "avianos",
    "mooncat",
    "thebigbellrace",
    "waldorfsjourney",
    "divers",
    "rakshasa",
    "starwaspir",
    "nightmanor",
    "cyberowls",
    "bushidoball",
    "mortolii",
    "quibblerace",
    "velgress",
    "valbrace",
    "golfaria",
    "vainger",
    "overbold",
    "campanella",
    "caramelcaramel",
    "seasidedrive",
    "campanella3",
    "oniondelivery",
    "hotfoot",
    "miniandmax",
    "partyhouse",
    "elfazarshat",
    "bughunter",
    "fisthell",
    "pilotquest",
    "campanella2",
    "barbuta",
    "camouflage",
    "porgy",
    "planetzoldath",
    "hypercontender",
    "kickclub",
    "combatants",
    "devilition",
    "paintchase",
    "railheist",
    "mortol",
    "attactics",
  ],
  hidden: ["grimstone", "warptank", "rockonisland", "lordsofdiskonia"],
};

// const TOP_5_ENTRIES: ReadonlyArray<[Game, string]> = [
//   ["campanella", "5k"],
//   ["magicgarden", "6k"],
//   ["ninpek", "5k"],
//   ["starwaspir", "60k"],
//   ["caramelcaramel", "20k"],
//   ["kickclub", "25k"],
//   ["rakshasa", "10k"],
//   ["seasidedrive", "40k"],
//   ["paintchase", "240"],
// ];
// export const TOP_5_SCORES: Descriptions = Object.fromEntries(TOP_5_ENTRIES);
// export const TOP_5: OptionList = {
//   shown: [
//     "campanella",
//     "magicgarden",
//     "ninpek",
//     "kickclub",
//     "starwaspir",
//     "caramelcaramel",
//   ],
//   shown_if_on_card: ["rakshasa", "seasidedrive", "paintchase"],
//   hidden: [],
// };

export const TWO_LEVELS: OptionList = {
  shown: [
    "campanella",
    "pingolf",
    "kickclub",
    "mooncat",
    "campanella3",
    "blockkoala",
    "overbold",
    "velgress",
    "hypercontender",
    "camouflage",
    "warptank",
    "railheist",
    "attactics",
    "bushidoball",
    "paintchase",
    "thebigbellrace",
    "devilition",
    "hotfoot",
  ],
  shown_if_on_card: [
    "valbrace",
    "starwaspir",
    "campanella2",
    "combatants",
    "oniondelivery",
    "cyberowls",
    "bughunter",
    "avianos",
    "mortol",
    "fisthell",
    "elfazarshat",
    "caramelcaramel",
    "seasidedrive",
    "rakshasa",
    "partyhouse",
    "rockonisland",
    "lordsofdiskonia",
  ],
  hidden: [],
};

export const FOUR_LEVELS: OptionList = {
  shown: [
    "campanella",
    "pingolf",
    "kickclub",
    "mooncat",
    "overbold",
    "campanella3",
  ],
  shown_if_on_card: [
    "devilition",
    "camouflage",
    "warptank",
    "railheist",
    "attactics",
    "bushidoball",
    "hypercontender",
    "blockkoala",
    "paintchase",
    "hotfoot",
    "velgress",
    "thebigbellrace",
    "starwaspir",
    "oniondelivery",
    "fisthell",
    "elfazarshat",
    "seasidedrive",
    "campanella2",
    "combatants",
    "cyberowls",
    "bughunter",
    "avianos",
    "mortol",
    "caramelcaramel",
  ],
  hidden: ["rockonisland", "lordsofdiskonia", "valbrace", "partyhouse"],
};

export const EIGHT_LEVELS: OptionList = {
  shown: ["campanella", "pingolf", "kickclub", "mooncat"],
  shown_if_on_card: [
    "overbold",
    "devilition",
    "camouflage",
    "warptank",
    "railheist",
    "attactics",
    "hypercontender",
    "campanella3",
    "blockkoala",
    "paintchase",
    "thebigbellrace",
  ],
  hidden: [
    "campanella2",
    "combatants",
    "bughunter",
    "avianos",
    "mortol",
    "rockonisland",
    "lordsofdiskonia",
    "partyhouse",
  ],
};

// export const TWO_KEYS: OptionList = {
//   shown: [
//     "mortolii",
//     "waldorfsjourney",
//     "velgress",
//     "cyberowls",
//     "valbrace",
//     "nightmanor",
//   ],
//   shown_if_on_card: ["vainger"],
//   hidden: [],
// };

// export const TWO_CHESTS: OptionList = {
//   shown: [
//     "valbrace",
//     "divers",
//     "nightmanor",
//     "barbuta",
//     "grimstone",
//     "waldorfsjourney",
//   ],
//   shown_if_on_card: ["campanella2", "pilotquest", "elfazarshat"],
//   hidden: [],
// };

// export const TWO_SHOPS: OptionList = {
//   shown: [
//     "quibblerace",
//     "rockonisland",
//     "avianos",
//     "waldorfsjourney",
//     "lordsofdiskonia",
//   ],
//   shown_if_on_card: [
//     "pilotquest",
//     "velgress",
//     "grimstone",
//     "miniandmax",
//     "campanella2",
//     "fisthell",
//     "barbuta",
//     "planetzoldath",
//     "valbrace",
//   ],
//   hidden: [],
// };

// export const TWO_LIVES: OptionList = {
//   shown: [
//     "campanella",
//     "waldorfsjourney",
//     "mortol",
//     "cyberowls",
//     "rakshasa",
//     "seasidedrive",
//     "kickclub",
//     "ninpek",
//     "elfazarshat",
//     "starwaspir",
//     "caramelcaramel",
//   ],
//   shown_if_on_card: ["barbuta", "vainger", "campanella3", "paintchase"],
//   hidden: [],
// };

// export const TWO_HP: OptionList = {
//   shown: [
//     "porgy",
//     "golfaria",
//     "overbold",
//     "valbrace",
//     "planetzoldath",
//     "miniandmax",
//     "divers",
//     "vainger",
//     "campanella2",
//     "grimstone",
//   ],
//   shown_if_on_card: [],
//   hidden: [],
// };

export const BOSSES: OptionList = {
  shown: [
    { type: "include", has_extra: "OPEN-TOMB", option: "mortol" },
    { type: "include", has_extra: "EVEN-COAT", option: "paintchase" },
    { type: "include", has_extra: "WORM-1234", option: "blockkoala" },
    "campanella",
    "rakshasa",
    "mortolii",
    "starwaspir",
    "fisthell",
    "miniandmax",
    "elfazarshat",
    "cyberowls",
    "seasidedrive",
    "kickclub",
    "campanella2",
  ],
  shown_if_on_card: [
    "caramelcaramel",
    "pilotquest",
    { type: "include", has_extra: "LAZY-COPS", option: "railheist" },
    { type: "include", has_extra: "ANTS-ANTS", option: "combatants" },
    "vainger",
    "campanella3",
    "velgress",
    "mooncat",
    "porgy",
    "hotfoot",
    "barbuta",
    "rockonisland",
    "overbold",
    "ninpek",
    "valbrace",
    "nightmanor",
  ],
  hidden: [
    "grimstone",
    "devilition",
    { type: "exclude", has_extra: "EVEN-COAT", option: "paintchase" },
    "divers",
    "golfaria",
    { type: "exclude", has_extra: "OPEN-TOMB", option: "mortol" },
    "warptank",
    { type: "exclude", has_extra: "LAZY-COPS", option: "railheist" },
    { type: "exclude", has_extra: "ANTS-ANTS", option: "combatants" },
    { type: "exclude", has_extra: "WORM-1234", option: "blockkoala" },
    "lordsofdiskonia",
  ],
};

export const TWO_BOSSES: OptionList = {
  shown: [
    "mortolii",
    "rakshasa",
    "elfazarshat",
    "campanella",
    "starwaspir",
    "fisthell",
    "caramelcaramel",
    "cyberowls",
    "campanella2",
  ],
  shown_if_on_card: [
    "seasidedrive",
    "campanella3",
    "kickclub",
    "vainger",
    "miniandmax",
    "barbuta",
    "hotfoot",
    "mooncat",
    "pilotquest",
    "porgy",
  ],
  hidden: [
    "rockonisland",
    "ninpek",
    "valbrace",
    "warptank",
    "divers",
    "grimstone",
  ],
};

// export const SIX_ENEMIES: OptionList = {
//   shown: [
//     { type: "include", has_extra: "EVEN-COAT", option: "paintchase" },
//     "cyberowls",
//     "bughunter",
//     "caramelcaramel",
//     "mortolii",
//     "elfazarshat",
//     "attactics",
//     "campanella2",
//     { type: "include", has_extra: "OPEN-TOMB", option: "mortol" },
//     "porgy",
//     "overbold",
//     "rakshasa",
//     "velgress",
//     "mooncat",
//     "warptank",
//     "miniandmax",
//     "ninpek",
//     "hotfoot",
//     "campanella",
//     "vainger",
//   ],
//   shown_if_on_card: [
//     "campanella3",
//     "kickclub",
//     "starwaspir",
//     "pingolf",
//     "seasidedrive",
//     "barbuta",
//     "bushidoball",
//     "golfaria",
//     "divers",
//     "grimstone",
//     "valbrace",
//     "fisthell",
//     "hypercontender",
//     "planetzoldath",
//     "lordsofdiskonia",
//     "pilotquest",
//     { type: "exclude", has_extra: "EVEN-COAT", option: "paintchase" },
//     { type: "exclude", has_extra: "OPEN-TOMB", option: "mortol" },
//     "rockonisland",
//   ],
//   hidden: [],
// };

// GIFT ESTIMATES
// ["magicgarden", 0.5],
// ["blockkoala", 0.5],
// ["pingolf", 0.5],
// ["ninpek", 1],
// ["avianos", 1],
// ["mooncat", 1],
// ["thebigbellrace", 1],
// ["waldorfsjourney", 1],
// ["divers", 1],
// ["rakshasa", 1],
// ["starwaspir", 1],
// ["nightmanor", 1],
// ["cyberowls", 1],
// ["bushidoball", 1.5],
// ["mortolii", 1.5],
// ["quibblerace", 1.5],
// ["velgress", 2],
// ["valbrace", 2],
// ["golfaria", 2.5],
// ["vainger", 2.5],
// ["overbold", 2.5],
// ["campanella", 2.8],
// ["caramelcaramel", 3],
// ["seasidedrive", 3],
// ["campanella3", 3],
// ["oniondelivery", 3],
// ["hotfoot", 3],
// ["miniandmax", 3],
// ["partyhouse", 3.5],
// ["elfazarshat", 3.5],
// ["bughunter", 3.8],
// ["fisthell", 4],
// ["pilotquest", 4],
// ["campanella2", 4.5],
// ["barbuta", 5],
// ["camouflage", 5],
// ["porgy", 5],
// ["planetzoldath", 6],
// ["hypercontender", 6],
// ["kickclub", 7],
// ["combatants", 7],
// ["devilition", 8],
// ["paintchase", 9],
// ["railheist", 12],
// ["mortol", 13],
// ["attactics", 20],
// ["grimstone", 20],
// ["warptank", 30],
// ["rockonisland", 30],
// ["lordsofdiskonia", 60],

// GOLD ESTIMATES
// ["nightmanor", 2.5],
// ["mortolii", 2.5],
// ["waldorfsjourney", 2.5],
// ["bushidoball", 3.5],
// ["velgress", 3],
// ["mooncat", 4],
// ["magicgarden", 5],
// ["pingolf", 5],
// ["quibblerace", 5],
// ["barbuta", 5.5],
// ["camouflage", 5.5],
// ["hotfoot", 6],
// ["overbold", 7],
// ["hypercontender", 8],
// ["starwaspir", 8],
// ["ninpek", 8.5],
// ["thebigbellrace", 8.5],
// ["oniondelivery", 10],
// ["rakshasa", 10],
// ["campanella", 13],
// ["caramelcaramel", 12],
// ["kickclub", 13],
// ["seasidedrive", 14],
// ["campanella2", 13],
// ["campanella3", 14],
// ["fisthell", 13],
// ["elfazarshat", 13],
// ["planetzoldath", 15],
// ["avianos", 15],
// ["bughunter", 12],
// ["devilition", 18],
// ["partyhouse", 18],
// ["cyberowls", 20],
// ["miniandmax", 25],
// ["paintchase", 20],
// ["mortol", 30],
// ["attactics", 30],
// ["golfaria", 35],
// ["combatants", 35],
// ["warptank", 40],
// ["railheist", 40],
// ["porgy", 45],
// ["blockkoala", 60],
// ["divers", 60],
// ["vainger", 60],
// ["rockonisland", 60],
// ["valbrace", 70],
// ["grimstone", 120],
// ["lordsofdiskonia", 180],
// ["pilotquest", 240],

// CHERRY ESTIMATES
// ["mortolii", 3],
// ["bushidoball", 3.5],
// ["waldorfsjourney", 3.5],
// ["velgress", 4],
// ["magicgarden", 5],
// ["pingolf", 5],
// ["barbuta", 5.5],
// ["hotfoot", 6],
// ["quibblerace", 6],
// ["overbold", 7],
// ["nightmanor", 7],
// ["starwaspir", 8],
// ["thebigbellrace", 8.5],
// ["rakshasa", 10],
// ["kickclub", 13],
// ["fisthell", 13],
// ["campanella2", 13],
// ["caramelcaramel", 14],
// ["elfazarshat", 14],
// ["seasidedrive", 14],
// ["campanella3", 14],
// ["planetzoldath", 15],
// ["camouflage", 15],
// ["mooncat", 16],
// ["campanella", 16],
// ["oniondelivery", 16],
// ["hypercontender", 16],
// ["ninpek", 17.5],
// ["devilition", 18],
// ["paintchase", 20],
// ["cyberowls", 20],
// ["partyhouse", 25],
// ["bughunter", 30],
// ["mortol", 30],
// ["avianos", 40],
// ["attactics", 60],
// ["divers", 60],
// ["railheist", 60],
// ["vainger", 60],
// ["miniandmax", 60],
// ["combatants", 60],
// ["blockkoala", 70],
// ["golfaria", 70],
// ["valbrace", 70],
// ["warptank", 80],
// ["rockonisland", 80],
// ["porgy", 90],
// ["grimstone", 180],
// ["lordsofdiskonia", 240],
// ["pilotquest", 240],
